services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
      #- "/dev/dri/card0:/dev/dri/card0"
      #- "/dev/dri/renderD128:/dev/dri/renderD128"
      #- "/dev/dri/renderD129:/dev/dri/renderD129"
    environment:
      - OLLAMA_INTEL_GPU=true
      - OLLAMA_HOST=0.0.0.0

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - APP_BASE_URL=http://ollama.internal
    volumes:
      - ollamaui_data:/app/backend/data

volumes:
  ollama_data:
    name: ollama_data
  ollamaui_data:
    name: ollamaui_data